export interface Profile {
  id: number
  name: string
  username: string
  age: number
  status: "online" | "active" | "inactive"
  distance: string
  bio: string
  images: string[]
  interests: string[]
  lookingFor: string
  height?: string
  occupation?: string
  education?: string
  photoGallery: string[]
  videoGallery: number
}

export const profiles: Profile[] = [
  {
    id: 1,
    name: "Anna",
    username: "anna_26",
    age: 26,
    status: "online",
    distance: "1 km",
    bio: "Uwielbiam podróże, dobrą kawę i długie spacery po mieście. Szukam kogoś, z kim będę mogła dzielić się swoimi pasjami.",
    images: [
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Podróże", "Kawa", "Spacery", "Fotografia"],
    lookingFor: "Szukam kogoś do wspólnych przygód i odkrywania nowych miejsc",
    height: "168 cm",
    occupation: "Marketing Manager",
    education: "Wyższe",
    photoGallery: [
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
    ],
    videoGallery: 2,
  },
  {
    id: 2,
    name: "Michał",
    username: "michal_fit",
    age: 29,
    status: "active",
    distance: "3 km",
    bio: "Pasjonat sportu i zdrowego stylu życia. W wolnym czasie gram w piłkę nożną i jeżdżę na rowerze.",
    images: [
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Sport", "Fitness", "Piłka nożna", "Rower"],
    lookingFor: "Szukam aktywnej osoby, która lubi sport i zdrowy tryb życia",
    height: "182 cm",
    occupation: "Trener personalny",
    education: "Wyższe",
    photoGallery: ["/male-avatar-default-profile-silhouette.jpg", "/male-avatar-default-profile-silhouette.jpg"],
    videoGallery: 1,
  },
  {
    id: 3,
    name: "Kasia",
    username: "kasia_art",
    age: 24,
    status: "online",
    distance: "5 km",
    bio: "Miłośniczka sztuki i dobrej muzyki. Pracuję jako grafik i w wolnym czasie maluję.",
    images: [
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Sztuka", "Muzyka", "Malarstwo", "Design"],
    lookingFor: "Szukam kogoś kreatywnego, kto rozumie sztukę i ma otwartą głowę",
    height: "165 cm",
    occupation: "Grafik",
    education: "Wyższe - ASP",
    photoGallery: ["/female-avatar-default-profile-silhouette.jpg", "/female-avatar-default-profile-silhouette.jpg"],
    videoGallery: 3,
  },
  {
    id: 4,
    name: "Patryk",
    username: "patryk_biz",
    age: 31,
    status: "inactive",
    distance: "7 km",
    bio: "Przedsiębiorca i miłośnik dobrego jedzenia. Szukam kogoś, z kim będę mógł odkrywać nowe restauracje.",
    images: [
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Biznes", "Gotowanie", "Restauracje", "Wino"],
    lookingFor: "Szukam kobiety, która ceni dobre jedzenie i lubi nowe doświadczenia",
    height: "178 cm",
    occupation: "Przedsiębiorca",
    education: "Wyższe - MBA",
    photoGallery: ["/male-avatar-default-profile-silhouette.jpg", "/male-avatar-default-profile-silhouette.jpg"],
    videoGallery: 0,
  },
  {
    id: 5,
    name: "Ola",
    username: "ola_yoga",
    age: 27,
    status: "active",
    distance: "10 km",
    bio: "Nauczycielka z pasją do czytania i jogi. Cenię sobie spokojne wieczory z dobrą książką.",
    images: [
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Joga", "Czytanie", "Medytacja", "Natura"],
    lookingFor: "Szukam spokojnej osoby, która ceni równowagę i rozwój duchowy",
    height: "170 cm",
    occupation: "Nauczycielka",
    education: "Wyższe",
    photoGallery: ["/female-avatar-default-profile-silhouette.jpg", "/female-avatar-default-profile-silhouette.jpg"],
    videoGallery: 4,
  },
  {
    id: 6,
    name: "Tomek",
    username: "tomek_dev",
    age: 28,
    status: "online",
    distance: "12 km",
    bio: "Programista i gamer. W wolnym czasie gram w gry komputerowe i uczę się nowych technologii.",
    images: [
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Programowanie", "Gaming", "Technologia", "AI"],
    lookingFor: "Szukam kogoś, kto rozumie świat technologii i lubi gry",
    height: "175 cm",
    occupation: "Software Developer",
    education: "Wyższe - Informatyka",
    photoGallery: ["/male-avatar-default-profile-silhouette.jpg", "/male-avatar-default-profile-silhouette.jpg"],
    videoGallery: 1,
  },
  {
    id: 7,
    name: "Magda",
    username: "magda_photo",
    age: 35,
    status: "active",
    distance: "15 km",
    bio: "Fotografka i podróżniczka. Uwielbiam odkrywać nowe miejsca i uwieczniać piękne chwile.",
    images: [
      "/realistic-selfie-photo-ordinary-woman-35-years-old.jpg",
      "/realistic-selfie-photo-ordinary-woman-35-years-old.jpg",
      "/realistic-selfie-photo-ordinary-woman-35-years-old.jpg",
    ],
    interests: ["Fotografia", "Podróże", "Przyroda", "Przygoda"],
    lookingFor: "Szukam kogoś, kto lubi podróżować i odkrywać świat",
    height: "172 cm",
    occupation: "Fotografka",
    education: "Wyższe",
    photoGallery: [
      "/realistic-selfie-photo-ordinary-woman-35-years-old.jpg",
      "/realistic-selfie-photo-ordinary-woman-35-years-old.jpg",
    ],
    videoGallery: 5,
  },
  {
    id: 8,
    name: "Jakub",
    username: "jakub_arch",
    age: 37,
    status: "inactive",
    distance: "18 km",
    bio: "Architekt z miłością do designu. Projektuję wnętrza i buduję marzenia.",
    images: [
      "/realistic-selfie-photo-ordinary-man-37-years-old-c.jpg",
      "/realistic-selfie-photo-ordinary-man-37-years-old-c.jpg",
      "/realistic-selfie-photo-ordinary-man-37-years-old-c.jpg",
    ],
    interests: ["Architektura", "Design", "Sztuka", "Minimalizm"],
    lookingFor: "Szukam kogoś z poczuciem estetyki i miłością do piękna",
    height: "180 cm",
    occupation: "Architekt",
    education: "Wyższe - Politechnika",
    photoGallery: [
      "/realistic-selfie-photo-ordinary-man-37-years-old-c.jpg",
      "/realistic-selfie-photo-ordinary-man-37-years-old-c.jpg",
    ],
    videoGallery: 2,
  },
  {
    id: 9,
    name: "Ania",
    username: "ania_med",
    age: 33,
    status: "online",
    distance: "20 km",
    bio: "Lekarka i wolontariuszka. Pomagam innym i uczę się ratować życie.",
    images: [
      "/realistic-selfie-photo-ordinary-woman-33-years-old.jpg",
      "/realistic-selfie-photo-ordinary-woman-33-years-old.jpg",
      "/realistic-selfie-photo-ordinary-woman-33-years-old.jpg",
    ],
    interests: ["Medycyna", "Wolontariat", "Nauka", "Pomaganie"],
    lookingFor: "Szukam kogoś empatycznego, kto rozumie wartość pomagania innym",
    height: "166 cm",
    occupation: "Lekarka",
    education: "Wyższe",
    photoGallery: [
      "/realistic-selfie-photo-ordinary-woman-33-years-old.jpg",
      "/realistic-selfie-photo-ordinary-woman-33-years-old.jpg",
    ],
    videoGallery: 1,
  },
  {
    id: 10,
    name: "Bartek",
    username: "bartek_music",
    age: 32,
    status: "active",
    distance: "25 km",
    bio: "Muzyk i kompozytor. Gram na gitarze i tworzę własną muzykę. Szukam kogoś, kto podziela moją pasję.",
    images: [
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
      "/male-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Muzyka", "Gitara", "Komponowanie", "Koncerty"],
    lookingFor: "Szukam kogoś, kto kocha muzykę i lubi chodzić na koncerty",
    height: "177 cm",
    occupation: "Muzyk",
    education: "Wyższe - Akademia Muzyczna",
    photoGallery: ["/male-avatar-default-profile-silhouette.jpg", "/male-avatar-default-profile-silhouette.jpg"],
    videoGallery: 3,
  },
  {
    id: 11,
    name: "Emilia",
    username: "emilkaa_ree",
    age: 25,
    status: "online",
    distance: "2 km",
    bio: "Jestem osobą pełną energii, która uwielbia spontaniczne przygody i nowe doświadczenia. W wolnym czasie trenuję taniec, spotykam się ze znajomymi i odkrywam nowe miejsca w mieście. Cenię sobie szczerość, poczucie humoru i głębokie rozmowy przy lampce wina.",
    images: [
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
      "/female-avatar-default-profile-silhouette.jpg",
    ],
    interests: ["Taniec", "Podróże", "Fotografia", "Joga", "Kino", "Gotowanie"],
    lookingFor:
      "Szukam kogoś, kto jest otwarty na nowe doświadczenia i potrafi cieszyć się chwilą. Ważna jest dla mnie szczerość i poczucie humoru.",
    height: "169 cm",
    occupation: "Instruktorka tańca",
    education: "Wyższe",
    photoGallery: ["/female-avatar-default-profile-silhouette.jpg", "/female-avatar-default-profile-silhouette.jpg"],
    videoGallery: 6,
  },
]

// Recently registered users (mix of existing profiles and new ones)
export const recentlyRegistered = [
  { name: "Zosia", username: "zosia_23", hasPhoto: false, gender: "female" },
  { name: "Marek", username: "marek_fit", hasPhoto: false, gender: "male" },
  {
    name: "Julia",
    username: "julia_art",
    hasPhoto: true,
    photo: "/realistic-selfie-ordinary-woman-32.jpg",
    gender: "female",
  },
  { name: "Damian", username: "damian_28", hasPhoto: false, gender: "male" },
  { name: "Weronika", username: "wera_smile", hasPhoto: false, gender: "female" },
  { name: "Łukasz", username: "lukasz_dev", hasPhoto: false, gender: "male" },
  { name: "Natalia", username: "natalia_24", hasPhoto: false, gender: "female" },
  { name: "Kamil", username: "kamil_sport", hasPhoto: false, gender: "male" },
  { name: "Paulina", username: "paula_travel", hasPhoto: false, gender: "female" },
  {
    name: "Adrian",
    username: "adrian_30",
    hasPhoto: true,
    photo: "/realistic-selfie-ordinary-man-34.jpg",
    gender: "male",
  },
  { name: "Martyna", username: "martyna_yoga", hasPhoto: false, gender: "female" },
  { name: "Piotr", username: "piotr_biz", hasPhoto: false, gender: "male" },
  {
    name: "Karolina",
    username: "karolina_26",
    hasPhoto: true,
    photo: "/realistic-selfie-ordinary-woman-31.jpg",
    gender: "female",
  },
  { name: "Mateusz", username: "mateusz_music", hasPhoto: false, gender: "male" },
  { name: "Aleksandra", username: "ola_photo", hasPhoto: false, gender: "female" },
  { name: "Rafał", username: "rafal_32", hasPhoto: false, gender: "male" },
  { name: "Dominika", username: "domi_dance", hasPhoto: false, gender: "female" },
  { name: "Krzysztof", username: "krzysiek_27", hasPhoto: false, gender: "male" },
  { name: "Monika", username: "monika_smile", hasPhoto: false, gender: "female" },
  { name: "Sebastian", username: "seba_fit", hasPhoto: false, gender: "male" },
]
